/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardCustomersRouteImport } from './routes/dashboard/customers'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard/notifications'
import { Route as DashboardProductsRouteImport } from './routes/dashboard/products'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as DashboardVendorsRouteImport } from './routes/dashboard/vendors'
import { Route as DashboardOrdersIndexRouteImport } from './routes/dashboard/orders/index'
import { Route as DashboardSettingsCompanyRouteImport } from './routes/dashboard/settings/company'
import { Route as DashboardSettingsEmployeesRouteImport } from './routes/dashboard/settings/employees'
import { Route as DashboardSettingsLookupsRouteImport } from './routes/dashboard/settings/lookups'
import { Route as DashboardSettingsRolesRouteImport } from './routes/dashboard/settings/roles'
import { Route as DashboardSettingsRulesRouteImport } from './routes/dashboard/settings/rules'
import { Route as DashboardSettingsStationsRouteImport } from './routes/dashboard/settings/stations'
import { Route as DashboardSystemActivityLogsRouteImport } from './routes/dashboard/system/activity-logs'
import { Route as DashboardSystemAuditLogsRouteImport } from './routes/dashboard/system/audit-logs'
import { Route as DashboardSystemChangelogRouteImport } from './routes/dashboard/system/changelog'
import { Route as DashboardSystemConfigsRouteImport } from './routes/dashboard/system/configs'
import { Route as DashboardSystemErrorLogsRouteImport } from './routes/dashboard/system/error-logs'
import { Route as DashboardSystemMenusRouteImport } from './routes/dashboard/system/menus'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCustomersRoute = DashboardCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProductsRoute = DashboardProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardVendorsRoute = DashboardVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrdersIndexRoute = DashboardOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsCompanyRoute =
  DashboardSettingsCompanyRouteImport.update({
    id: '/settings/company',
    path: '/settings/company',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSettingsEmployeesRoute =
  DashboardSettingsEmployeesRouteImport.update({
    id: '/settings/employees',
    path: '/settings/employees',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSettingsLookupsRoute =
  DashboardSettingsLookupsRouteImport.update({
    id: '/settings/lookups',
    path: '/settings/lookups',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSettingsRolesRoute = DashboardSettingsRolesRouteImport.update({
  id: '/settings/roles',
  path: '/settings/roles',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRulesRoute = DashboardSettingsRulesRouteImport.update({
  id: '/settings/rules',
  path: '/settings/rules',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsStationsRoute =
  DashboardSettingsStationsRouteImport.update({
    id: '/settings/stations',
    path: '/settings/stations',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSystemActivityLogsRoute =
  DashboardSystemActivityLogsRouteImport.update({
    id: '/system/activity-logs',
    path: '/system/activity-logs',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSystemAuditLogsRoute =
  DashboardSystemAuditLogsRouteImport.update({
    id: '/system/audit-logs',
    path: '/system/audit-logs',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSystemChangelogRoute =
  DashboardSystemChangelogRouteImport.update({
    id: '/system/changelog',
    path: '/system/changelog',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSystemConfigsRoute = DashboardSystemConfigsRouteImport.update({
  id: '/system/configs',
  path: '/system/configs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSystemErrorLogsRoute =
  DashboardSystemErrorLogsRouteImport.update({
    id: '/system/error-logs',
    path: '/system/error-logs',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSystemMenusRoute = DashboardSystemMenusRouteImport.update({
  id: '/system/menus',
  path: '/system/menus',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/products': typeof DashboardProductsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/vendors': typeof DashboardVendorsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/settings/company': typeof DashboardSettingsCompanyRoute
  '/dashboard/settings/employees': typeof DashboardSettingsEmployeesRoute
  '/dashboard/settings/lookups': typeof DashboardSettingsLookupsRoute
  '/dashboard/settings/roles': typeof DashboardSettingsRolesRoute
  '/dashboard/settings/rules': typeof DashboardSettingsRulesRoute
  '/dashboard/settings/stations': typeof DashboardSettingsStationsRoute
  '/dashboard/system/activity-logs': typeof DashboardSystemActivityLogsRoute
  '/dashboard/system/audit-logs': typeof DashboardSystemAuditLogsRoute
  '/dashboard/system/changelog': typeof DashboardSystemChangelogRoute
  '/dashboard/system/configs': typeof DashboardSystemConfigsRoute
  '/dashboard/system/error-logs': typeof DashboardSystemErrorLogsRoute
  '/dashboard/system/menus': typeof DashboardSystemMenusRoute
  '/dashboard/orders/': typeof DashboardOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/products': typeof DashboardProductsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/vendors': typeof DashboardVendorsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/settings/company': typeof DashboardSettingsCompanyRoute
  '/dashboard/settings/employees': typeof DashboardSettingsEmployeesRoute
  '/dashboard/settings/lookups': typeof DashboardSettingsLookupsRoute
  '/dashboard/settings/roles': typeof DashboardSettingsRolesRoute
  '/dashboard/settings/rules': typeof DashboardSettingsRulesRoute
  '/dashboard/settings/stations': typeof DashboardSettingsStationsRoute
  '/dashboard/system/activity-logs': typeof DashboardSystemActivityLogsRoute
  '/dashboard/system/audit-logs': typeof DashboardSystemAuditLogsRoute
  '/dashboard/system/changelog': typeof DashboardSystemChangelogRoute
  '/dashboard/system/configs': typeof DashboardSystemConfigsRoute
  '/dashboard/system/error-logs': typeof DashboardSystemErrorLogsRoute
  '/dashboard/system/menus': typeof DashboardSystemMenusRoute
  '/dashboard/orders': typeof DashboardOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/products': typeof DashboardProductsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/vendors': typeof DashboardVendorsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/settings/company': typeof DashboardSettingsCompanyRoute
  '/dashboard/settings/employees': typeof DashboardSettingsEmployeesRoute
  '/dashboard/settings/lookups': typeof DashboardSettingsLookupsRoute
  '/dashboard/settings/roles': typeof DashboardSettingsRolesRoute
  '/dashboard/settings/rules': typeof DashboardSettingsRulesRoute
  '/dashboard/settings/stations': typeof DashboardSettingsStationsRoute
  '/dashboard/system/activity-logs': typeof DashboardSystemActivityLogsRoute
  '/dashboard/system/audit-logs': typeof DashboardSystemAuditLogsRoute
  '/dashboard/system/changelog': typeof DashboardSystemChangelogRoute
  '/dashboard/system/configs': typeof DashboardSystemConfigsRoute
  '/dashboard/system/error-logs': typeof DashboardSystemErrorLogsRoute
  '/dashboard/system/menus': typeof DashboardSystemMenusRoute
  '/dashboard/orders/': typeof DashboardOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/customers'
    | '/dashboard/notifications'
    | '/dashboard/products'
    | '/dashboard/profile'
    | '/dashboard/vendors'
    | '/dashboard/'
    | '/dashboard/settings/company'
    | '/dashboard/settings/employees'
    | '/dashboard/settings/lookups'
    | '/dashboard/settings/roles'
    | '/dashboard/settings/rules'
    | '/dashboard/settings/stations'
    | '/dashboard/system/activity-logs'
    | '/dashboard/system/audit-logs'
    | '/dashboard/system/changelog'
    | '/dashboard/system/configs'
    | '/dashboard/system/error-logs'
    | '/dashboard/system/menus'
    | '/dashboard/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/customers'
    | '/dashboard/notifications'
    | '/dashboard/products'
    | '/dashboard/profile'
    | '/dashboard/vendors'
    | '/dashboard'
    | '/dashboard/settings/company'
    | '/dashboard/settings/employees'
    | '/dashboard/settings/lookups'
    | '/dashboard/settings/roles'
    | '/dashboard/settings/rules'
    | '/dashboard/settings/stations'
    | '/dashboard/system/activity-logs'
    | '/dashboard/system/audit-logs'
    | '/dashboard/system/changelog'
    | '/dashboard/system/configs'
    | '/dashboard/system/error-logs'
    | '/dashboard/system/menus'
    | '/dashboard/orders'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/customers'
    | '/dashboard/notifications'
    | '/dashboard/products'
    | '/dashboard/profile'
    | '/dashboard/vendors'
    | '/dashboard/'
    | '/dashboard/settings/company'
    | '/dashboard/settings/employees'
    | '/dashboard/settings/lookups'
    | '/dashboard/settings/roles'
    | '/dashboard/settings/rules'
    | '/dashboard/settings/stations'
    | '/dashboard/system/activity-logs'
    | '/dashboard/system/audit-logs'
    | '/dashboard/system/changelog'
    | '/dashboard/system/configs'
    | '/dashboard/system/error-logs'
    | '/dashboard/system/menus'
    | '/dashboard/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/customers': {
      id: '/dashboard/customers'
      path: '/customers'
      fullPath: '/dashboard/customers'
      preLoaderRoute: typeof DashboardCustomersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/products': {
      id: '/dashboard/products'
      path: '/products'
      fullPath: '/dashboard/products'
      preLoaderRoute: typeof DashboardProductsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/vendors': {
      id: '/dashboard/vendors'
      path: '/vendors'
      fullPath: '/dashboard/vendors'
      preLoaderRoute: typeof DashboardVendorsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/orders/': {
      id: '/dashboard/orders/'
      path: '/orders'
      fullPath: '/dashboard/orders/'
      preLoaderRoute: typeof DashboardOrdersIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings/company': {
      id: '/dashboard/settings/company'
      path: '/settings/company'
      fullPath: '/dashboard/settings/company'
      preLoaderRoute: typeof DashboardSettingsCompanyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings/employees': {
      id: '/dashboard/settings/employees'
      path: '/settings/employees'
      fullPath: '/dashboard/settings/employees'
      preLoaderRoute: typeof DashboardSettingsEmployeesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings/lookups': {
      id: '/dashboard/settings/lookups'
      path: '/settings/lookups'
      fullPath: '/dashboard/settings/lookups'
      preLoaderRoute: typeof DashboardSettingsLookupsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings/roles': {
      id: '/dashboard/settings/roles'
      path: '/settings/roles'
      fullPath: '/dashboard/settings/roles'
      preLoaderRoute: typeof DashboardSettingsRolesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings/rules': {
      id: '/dashboard/settings/rules'
      path: '/settings/rules'
      fullPath: '/dashboard/settings/rules'
      preLoaderRoute: typeof DashboardSettingsRulesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings/stations': {
      id: '/dashboard/settings/stations'
      path: '/settings/stations'
      fullPath: '/dashboard/settings/stations'
      preLoaderRoute: typeof DashboardSettingsStationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/system/activity-logs': {
      id: '/dashboard/system/activity-logs'
      path: '/system/activity-logs'
      fullPath: '/dashboard/system/activity-logs'
      preLoaderRoute: typeof DashboardSystemActivityLogsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/system/audit-logs': {
      id: '/dashboard/system/audit-logs'
      path: '/system/audit-logs'
      fullPath: '/dashboard/system/audit-logs'
      preLoaderRoute: typeof DashboardSystemAuditLogsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/system/changelog': {
      id: '/dashboard/system/changelog'
      path: '/system/changelog'
      fullPath: '/dashboard/system/changelog'
      preLoaderRoute: typeof DashboardSystemChangelogRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/system/configs': {
      id: '/dashboard/system/configs'
      path: '/system/configs'
      fullPath: '/dashboard/system/configs'
      preLoaderRoute: typeof DashboardSystemConfigsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/system/error-logs': {
      id: '/dashboard/system/error-logs'
      path: '/system/error-logs'
      fullPath: '/dashboard/system/error-logs'
      preLoaderRoute: typeof DashboardSystemErrorLogsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/system/menus': {
      id: '/dashboard/system/menus'
      path: '/system/menus'
      fullPath: '/dashboard/system/menus'
      preLoaderRoute: typeof DashboardSystemMenusRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardCustomersRoute: typeof DashboardCustomersRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardProductsRoute: typeof DashboardProductsRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardVendorsRoute: typeof DashboardVendorsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardSettingsCompanyRoute: typeof DashboardSettingsCompanyRoute
  DashboardSettingsEmployeesRoute: typeof DashboardSettingsEmployeesRoute
  DashboardSettingsLookupsRoute: typeof DashboardSettingsLookupsRoute
  DashboardSettingsRolesRoute: typeof DashboardSettingsRolesRoute
  DashboardSettingsRulesRoute: typeof DashboardSettingsRulesRoute
  DashboardSettingsStationsRoute: typeof DashboardSettingsStationsRoute
  DashboardSystemActivityLogsRoute: typeof DashboardSystemActivityLogsRoute
  DashboardSystemAuditLogsRoute: typeof DashboardSystemAuditLogsRoute
  DashboardSystemChangelogRoute: typeof DashboardSystemChangelogRoute
  DashboardSystemConfigsRoute: typeof DashboardSystemConfigsRoute
  DashboardSystemErrorLogsRoute: typeof DashboardSystemErrorLogsRoute
  DashboardSystemMenusRoute: typeof DashboardSystemMenusRoute
  DashboardOrdersIndexRoute: typeof DashboardOrdersIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCustomersRoute: DashboardCustomersRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardProductsRoute: DashboardProductsRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardVendorsRoute: DashboardVendorsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardSettingsCompanyRoute: DashboardSettingsCompanyRoute,
  DashboardSettingsEmployeesRoute: DashboardSettingsEmployeesRoute,
  DashboardSettingsLookupsRoute: DashboardSettingsLookupsRoute,
  DashboardSettingsRolesRoute: DashboardSettingsRolesRoute,
  DashboardSettingsRulesRoute: DashboardSettingsRulesRoute,
  DashboardSettingsStationsRoute: DashboardSettingsStationsRoute,
  DashboardSystemActivityLogsRoute: DashboardSystemActivityLogsRoute,
  DashboardSystemAuditLogsRoute: DashboardSystemAuditLogsRoute,
  DashboardSystemChangelogRoute: DashboardSystemChangelogRoute,
  DashboardSystemConfigsRoute: DashboardSystemConfigsRoute,
  DashboardSystemErrorLogsRoute: DashboardSystemErrorLogsRoute,
  DashboardSystemMenusRoute: DashboardSystemMenusRoute,
  DashboardOrdersIndexRoute: DashboardOrdersIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
